### ISSUE TITLE
Check Sector codelist values for non-default vocabularies

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/IATI-Dashboard#15]
Relates to #6.

@stevieflow [points out](https://github.com/codeforIATI/IATI-Dashboard/issues/6#issuecomment-808055843) that we are currently only checking default vocabularies.

We no longer flag other vocabulary values as “Not on Codelist”, so that’s an improvement. But for embedded and non-embedded codelists, we could check and list whether codes from non-default vocabularies are members of their corresponding codelist.

Sector codes for UNHCR are a good example of this. They’re using [DAC 5 digit](https://codelists.codeforiati.org/Sector/) (vocabulary 1) but also [humanitarian global clusters](https://codelists.codeforiati.org/HumanitarianGlobalClusters/) (vocabulary 10):
https://dashboard.codeforiati.org/publisher/unhcr.html#p_codelists

**Comment by stevieflow** [comment]
Thanks @andylolz 

In terms of Sectors: https://codelists.codeforiati.org/SectorVocabulary/

Of these, I think we only have immediate access to check any values on vocabs 1, 2, 7, 8 & 10 (note: 10 is included in codeforiati codelists: https://codelists.codeforiati.org/HumanitarianGlobalClusters/ - but this source is not cited in the vocab table)

We cannot check the values on 98 & 98 --> I think that could be a whole other part of the dashboard!

Regarding sector vocabs 3, 4, 5, 6, 9 & 11 - I dont think we'd want/be able to pull these in to run a check...?

**Comment by stevieflow** [comment]
(updating title of ticket, as there are several instances of vocabs - so might be easier to focus on one-per-ticket)

**Comment by andylolz** [comment]
This is close to being done? See for example sector codes here:
https://dashboard.codeforiati.org/publisher/wfp.html#p_codelists

Unofficial codelists like sector vocab 10 (humanitarian global clusters) require some codeforIATI-specific mappings. I’ve added those in this PR: https://github.com/codeforIATI/Unofficial-Codelists/pull/130.

**Comment by stevieflow** [comment]
Amazing! 

I can see that it's also populating for other uses of vocabulary - eg AidType : https://dashboard.codeforiati.org/publisher/unhcr.html#p_codelists

**Comment by andylolz** [comment]
> I can see that it's also populating for other uses of vocabulary - eg AidType : https://dashboard.codeforiati.org/publisher/unhcr.html#p_codelists

Ooh, nice – that’s a good example. Yeah, it should be working for all mappings that are listed in IATI’s mapping file.

I noticed a couple that are missing, so I’ve sent a PR: IATI/IATI-Codelists 253

**Comment by andylolz** [comment]
Okay, I think unofficial codelists are sorted now too. E.g.:
https://dashboard.codeforiati.org/publisher/unhcr.html#p_codelists

**Comment by andylolz** [comment]
The default ordering is now weird, but that should be fixed on the next run.

Anyway, closing this! :tada:
