### ISSUE TITLE
Check Aid Type vocabulary values

### ISSUE THREAD

**Issue by stevieflow** [codeforIATI/IATI-Dashboard#19]
As with Sector ( https://github.com/codeforIATI/IATI-Dashboard/issues/15 )  codes, there are several vocabs where values can be checked aside from the default (vocab=1)

Of these:

https://codelists.codeforiati.org/AidTypeVocabulary/

voabs 2 & 4 exist already as codeforiati codelists, so these could be checked

vocab 3 doesnt - it's buried in a PDF  I've proposed that we coudl / should digitise this in https://github.com/codeforIATI/Unofficial-Codelists/issues/129

**Comment by andylolz** [comment]
Fixed in #20.
