### ISSUE TITLE
Codelist checks should deal with vocabularies

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/IATI-Dashboard#6]
The following notice appears on publisher pages, for some elements:
![Screenshot 2021-03-25 at 16 39 16](https://user-images.githubusercontent.com/464193/112509727-a5b36c00-8d88-11eb-8149-85e934aef251.png)

It would be good to implement a fix so that this notice is no longer required.

Originally reported by @stevieflow.

**Comment by andylolz** [comment]
@stevieflow does this look fixed? See for example:
https://dashboard.codeforiati.org/publisher/scuk.html#p_codelists

**Comment by andylolz** [comment]
@stevieflow does this look fixed? See for example:
https://dashboard.codeforiati.org/publisher/scuk.html#p_codelists

![Screenshot 2021-03-26 at 08 34 50](https://user-images.githubusercontent.com/464193/112604517-249eb800-8e0e-11eb-8e32-c656e8fd1dbb.png)

**Comment by stevieflow** [comment]
Thanks @andylolz 

Yes, that looks right

Here's a publisher that uses multiple sector vocabs: https://dashboard.codeforiati.org/publisher/unhcr.html#p_codelists

I guess what we don't currently check is the codes on vocabularies that are not the default..?  We would exclude any checks on 99 or 98 vocabs, as we dont know the codes, though...

**Comment by andylolz** [comment]
> We would exclude any checks on 99 or 98 vocabs, as we dont know the codes, though...

Yes, exactly.

> I guess what we don't currently check is the codes on vocabularies that are not the default..?

Ooh… That’s a very good point. Okay, but let’s make a new ticket in order to address that.
