### ISSUE TITLE
default-aid-type defaults to CashandVoucherModalities vocabulary

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/IATI-Dashboard#7]
**Describe the bug**
The analysis of default-aid-type defaults to the CashandVoucherModalities vocabulary, meaning that those that used the documented default vocabulary are flagged

See: https://dashboard.codeforiati.org/codelist/2/default-aid-type_@code.html

**To Reproduce**
Steps to reproduce the behaviour:
Go to https://dashboard.codeforiati.org/codelist/2/default-aid-type_@code.html

See example publisher: https://dashboard.codeforiati.org/publisher/afdb.html#p_codelists

**Expected behaviour**
A publisher should be checked against values on the default vocabulary: http://reference.iatistandard.org/203/codelists/AidType/

Originally reported by @stevieflow.

**Comment by andylolz** [comment]
Oops – I’ll leave this issue open until the dashboard next builds, so we can check it IRL.

**Comment by andylolz** [comment]
@stevieflow does this look fixed? See for example:
https://dashboard.codeforiati.org/publisher/scuk.html#p_codelists

**Comment by andylolz** [comment]
@stevieflow does this look fixed? See for example:
https://dashboard.codeforiati.org/publisher/scuk.html#p_codelists

![Screenshot 2021-03-26 at 08 34 06](https://user-images.githubusercontent.com/464193/112604439-0afd7080-8e0e-11eb-9470-9cd8ab4fd40d.png)

**Comment by stevieflow** [comment]
Thanks @andylolz 

Yep, great

I guess the same issue then arises - when publishers use multiple vocabularies for transaction/aid-type...

**Comment by andylolz** [comment]
Yep, agreed. So, the default vocab is now sorted, but other vocabs (that refer to a codelist that exist inside IATI) are not.

Closing this one, but let’s make a new ticket for that.
